import { createFileRoute } from "@tanstack/react-router";
import { PageShell } from "@/components/layout/PageShell";
import { ArticleLayout } from "@/components/content/ArticleLayout";
import { buildMeta, canonical, breadcrumbLd, articleLd } from "@/lib/seo";

const TITLE = "The ChatGPT Image Watermark Explained — What It Is, Why It Exists";
const DESCRIPTION =
  "Why does ChatGPT watermark every image? What does the mark contain, what can it prove, and what are the risks of leaving it in your file?";
const PATH = "/chatgpt-image-watermark-explained";

export const Route = createFileRoute("/chatgpt-image-watermark-explained/")({
  head: () => ({
    meta: buildMeta({ title: TITLE, description: DESCRIPTION, path: PATH, type: "article" }),
    links: canonical(PATH),
    scripts: [
      breadcrumbLd([{ name: "ChatGPT Watermark Explained", path: PATH }]),
      articleLd({ headline: TITLE, description: DESCRIPTION, path: PATH, datePublished: "2026-04-10" }),
    ],
  }),
  component: () => (
    <PageShell>
      <ArticleLayout
        eyebrow="Explained"
        title="The ChatGPT Image Watermark, Explained"
        intro="Every image ChatGPT generates is silently signed. Here's the why, the what, and the so-what."
        breadcrumbs={[{ name: "ChatGPT Watermark Explained", path: PATH }]}
      >
        <h2>Why OpenAI watermarks every image</h2>
        <p>
          OpenAI signed onto the C2PA standard in 2024 as part of a broader industry pledge to
          make AI-generated content identifiable. The official rationale: combat misinformation,
          help platforms enforce disclosure rules, and build trust with regulators. The
          practical effect: every ChatGPT image is detectable as AI-generated by anyone with a
          C2PA-aware tool — instantly and with cryptographic certainty.
        </p>

        <h2>What the watermark actually is</h2>
        <p>
          It is <strong>not</strong> a visible mark. It is a JUMBF box appended to the image
          file containing a signed C2PA manifest with the model name, timestamp, and OpenAI's
          signing certificate. The pixels are untouched.
        </p>

        <h2>What it can prove</h2>
        <ul>
          <li>The image was generated by an OpenAI model</li>
          <li>The exact model and version</li>
          <li>The generation time</li>
          <li>That the pixels have not been altered since signing (the hash invalidates if you edit even one pixel)</li>
        </ul>

        <h2>The risks of leaving it in</h2>
        <ul>
          <li>Stock photo sites auto-reject the file</li>
          <li>Social platforms auto-label it "AI generated"</li>
          <li>Journalism workflows flag the source</li>
          <li>Your prompt context (sometimes embedded) leaks</li>
          <li>Clients can prove a "custom illustration" was actually AI</li>
        </ul>

        <h2>What to do about it</h2>
        <p>
          If you legitimately own the image (you do — OpenAI's Terms assign ownership to you)
          and want to use it without the AI provenance tag, use our{" "}
          <a href="/">free ChatGPT image watermark remover</a>. It strips the JUMBF box in your
          browser. See also: <a href="/c2pa-vs-visible-watermark">C2PA vs visible
          watermarks</a>.
        </p>
      </ArticleLayout>
    </PageShell>
  ),
});
