import { createFileRoute } from "@tanstack/react-router";
import { PageShell } from "@/components/layout/PageShell";
import { ArticleLayout } from "@/components/content/ArticleLayout";
import { buildMeta, canonical, breadcrumbLd, articleLd } from "@/lib/seo";

const TITLE = "What Is C2PA Metadata? (Complete Guide for ChatGPT Users)";
const DESCRIPTION =
  "C2PA is the invisible cryptographic provenance standard OpenAI embeds in every ChatGPT image. Learn what's inside, who reads it, and how to remove it.";
const PATH = "/what-is-c2pa-metadata";

export const Route = createFileRoute("/what-is-c2pa-metadata/")({
  head: () => ({
    meta: buildMeta({ title: TITLE, description: DESCRIPTION, path: PATH, type: "article" }),
    links: canonical(PATH),
    scripts: [
      breadcrumbLd([{ name: "What Is C2PA Metadata", path: PATH }]),
      articleLd({ headline: TITLE, description: DESCRIPTION, path: PATH, datePublished: "2026-05-01" }),
    ],
  }),
  component: () => (
    <PageShell>
      <ArticleLayout
        eyebrow="Learn"
        title="What Is C2PA Metadata?"
        intro="C2PA is the invisible 'made by AI' passport quietly embedded in every ChatGPT image. Here's exactly what it is, what's inside, and why it matters."
        breadcrumbs={[{ name: "What Is C2PA Metadata", path: PATH }]}
      >
        <h2>The 60-second version</h2>
        <p>
          C2PA stands for the <strong>Coalition for Content Provenance and Authenticity</strong>.
          It is an open standard, developed by Adobe, Microsoft, the BBC, Intel, Truepic and
          OpenAI, that embeds a tamper-evident cryptographic record into a media file. Think of
          it as a digital chain of custody — every editor, every camera, every AI model that
          touches the file can append a signed claim.
        </p>
        <p>
          For ChatGPT images, the relevant claim says: <em>"this image was generated by OpenAI's
          gpt-image-1 model at timestamp X, signed with our certificate."</em>
        </p>

        <h2>How it's stored inside the file</h2>
        <p>
          C2PA claims are packaged inside a JPEG/PNG/WebP using a container format called
          <strong> JUMBF</strong> (JPEG Universal Metadata Box Format). The magic bytes
          <code>6A 75 6D 62</code> mark the start of a JUMBF box, and our detector simply looks
          for those bytes plus a handful of ASCII identifiers like <code>c2pa</code> and
          <code>contentauthenticity</code>.
        </p>

        <h2>What's actually inside a ChatGPT C2PA manifest</h2>
        <ul>
          <li><strong>claim_generator</strong> — which OpenAI model produced the image</li>
          <li><strong>created</strong> — ISO 8601 generation timestamp</li>
          <li><strong>actions[]</strong> — list of generation steps</li>
          <li><strong>signature_info</strong> — issuer (OpenAI), signing cert, algorithm</li>
          <li><strong>hash</strong> — SHA-256 of the image bytes</li>
          <li><strong>thumbnail</strong> — a small preview embedded inside the file</li>
        </ul>

        <h2>Who reads it?</h2>
        <p>
          Adobe Photoshop, Microsoft Edge, social platforms (Meta is rolling it out), stock
          photo sites, journalism workflows, and any tool that integrates the C2PA SDK. Once
          they read the manifest they can show a "Made with AI" badge — or refuse the upload
          entirely.
        </p>

        <h2>How to remove it</h2>
        <p>
          Use our free <a href="/">ChatGPT image watermark remover</a>. It runs entirely in your
          browser, re-encodes the image through the HTML5 Canvas API, and produces a clean file
          with no JUMBF box. Verify the result with the <a href="/verify">verify tool</a>.
        </p>
      </ArticleLayout>
    </PageShell>
  ),
});
