import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

export const FAQ_ITEMS = [
  {
    q: "What is a ChatGPT image watermark?",
    a: "A ChatGPT image watermark is invisible C2PA (Coalition for Content Provenance and Authenticity) metadata embedded into every image generated by ChatGPT. It contains a cryptographic signature proving the image was AI-generated by OpenAI. It is not visible to the eye but can be detected by verification tools.",
  },
  {
    q: "How does the ChatGPT image watermark remover work?",
    a: "The tool reads your image file as raw binary data and scans for C2PA metadata markers (like JUMBF box signatures). It then uses the HTML5 Canvas API to redraw the image pixel-for-pixel onto a new canvas and exports it — creating a new image file with zero embedded metadata. This process runs 100% in your browser.",
  },
  {
    q: "Are my images uploaded to a server?",
    a: "No. Absolutely not. All processing happens client-side in your browser using JavaScript. Your images never leave your device, are never transmitted over the internet, and are never stored anywhere. The tool works entirely offline once the page is loaded.",
  },
  {
    q: "Does removing C2PA metadata affect image quality?",
    a: "No. The Canvas API re-encodes images at 97% JPEG quality or lossless PNG, preserving all visual detail, colors, dimensions, and sharpness. The only thing removed is the embedded metadata — the actual image pixels are completely unchanged.",
  },
  {
    q: "Can I remove watermarks from multiple ChatGPT images at once?",
    a: "Yes. The tool supports bulk processing of up to 50 images at a time. Upload them all at once, detect watermarks in parallel, then clean and download all with a single click.",
  },
  {
    q: "What image formats does this ChatGPT watermark remover support?",
    a: "The tool supports JPEG, PNG, and WebP — the three formats ChatGPT uses for image generation. Output format matches the input format for JPEG and PNG. WebP inputs are exported as PNG due to browser Canvas API limitations.",
  },
  {
    q: "Is it legal to remove C2PA metadata from ChatGPT images?",
    a: "Removing metadata from images you own or have the right to modify is generally legal in most jurisdictions. The tool is provided for legitimate purposes such as privacy, file optimization, and professional use. Always review OpenAI's Terms of Service and applicable laws for your specific use case.",
  },
  {
    q: "How do I verify the C2PA watermark was removed?",
    a: "After downloading your cleaned image, upload it to verify.contentauthenticity.org — the official C2PA verification tool. If the watermark was successfully removed, it will report 'No Content Credentials found.' You can also compare file sizes: cleaned images are typically a few KB smaller.",
  },
  {
    q: "Does this remove the visible Content Credentials symbol from ChatGPT images?",
    a: "No. This tool only removes the invisible C2PA metadata embedded in the file. The visible CR symbol (if present in the top-left corner) is part of the image pixels and requires image editing software like Photoshop or GIMP to remove visually.",
  },
  {
    q: "Does the tool work on mobile devices?",
    a: "Yes. The tool works on iOS and Android browsers (Chrome, Safari, Firefox) without any limitations. Drop or select images from your camera roll and clean them right on your phone.",
  },
  {
    q: "Will it remove EXIF and other metadata too?",
    a: "Yes. Because the cleaning step re-encodes the image through Canvas, every form of embedded metadata is stripped — C2PA, EXIF, IPTC, XMP, GPS coordinates and color profiles. You get a clean file containing only the pixels.",
  },
  {
    q: "Does it work on Sora and DALL·E images?",
    a: "Yes. Sora, DALL·E, and ChatGPT all use the same C2PA provenance system from OpenAI. The same JUMBF / C2PA markers are embedded and the same removal process works on all of them.",
  },
  {
    q: "Is the tool really free?",
    a: "Yes — it is 100% free with no signups, no watermarks added to your output, no daily limits, and no paid tier. The tool runs in your browser so there's no infrastructure to pay for.",
  },
  {
    q: "Will Google's SynthID or other watermarks be removed?",
    a: "This tool targets C2PA / JUMBF metadata specifically (the system used by OpenAI and many AI providers). It does not target pixel-level watermarks like SynthID that are encoded directly into image content.",
  },
  {
    q: "What happens to my original images?",
    a: "Nothing. The tool only reads them and produces a new cleaned file alongside. Your originals remain untouched on your device.",
  },
] as const;

export function FAQ() {
  return (
    <section id="faq" className="border-t border-border/60 bg-surface/40">
      <div className="mx-auto max-w-3xl px-6 py-24">
        <div className="mb-12 text-center">
          <p className="mb-3 text-xs font-semibold uppercase tracking-widest text-primary">
            FAQ
          </p>
          <h2 className="font-display text-4xl font-bold md:text-5xl">
            Frequently asked questions
          </h2>
        </div>

        <Accordion type="single" collapsible className="space-y-3">
          {FAQ_ITEMS.map((item, i) => (
            <AccordionItem
              key={i}
              value={`item-${i}`}
              className="overflow-hidden rounded-xl border border-border bg-background px-5"
            >
              <AccordionTrigger className="text-left font-display text-base font-semibold hover:no-underline">
                {item.q}
              </AccordionTrigger>
              <AccordionContent className="text-sm leading-relaxed text-muted-foreground">
                {item.a}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
}
