export function WhyRemove() {
  return (
    <section className="mx-auto max-w-4xl px-6 py-24">
      <div className="mb-10 text-center">
        <p className="mb-3 text-xs font-semibold uppercase tracking-widest text-primary">
          Why this matters
        </p>
        <h2 className="font-display text-4xl font-bold md:text-5xl">
          Why remove C2PA metadata from ChatGPT images?
        </h2>
      </div>

      <div className="space-y-6 text-[15px] leading-relaxed text-muted-foreground">
        <p>
          Every image generated by ChatGPT, DALL·E and Sora ships with invisible{" "}
          <strong className="text-foreground">C2PA metadata</strong> — a cryptographic
          signature from the Coalition for Content Provenance and Authenticity that
          identifies the file as AI-generated by OpenAI. You can't see it, but tools
          like <em>verify.contentauthenticity.org</em> can read it in seconds.
        </p>
        <p>
          A <strong className="text-foreground">chatgpt image watermark remover</strong>{" "}
          gives you back control over your own files. Whether you're a designer using AI
          for moodboards, a marketer producing concept art, or a creator who simply
          wants to ship clean exports, removing this hidden tag prevents the file from
          being flagged as ChatGPT output by downstream systems.
        </p>
        <p>
          Stripping C2PA metadata also{" "}
          <strong className="text-foreground">shrinks file size</strong> (every header
          byte counts at scale), removes the cryptographic signature from your asset,
          and produces a clean output you can hand off to clients, upload to stock
          platforms, or feed into your own design pipeline without unwanted provenance
          headers attached.
        </p>
      </div>
    </section>
  );
}
