export interface RelatedTool {
  slug: string;
  ai: string;
  brand: string;
  watermarkType: string;
  description: string;
  longDescription: string;
  hasC2PA: boolean;
}

export const RELATED_TOOLS: RelatedTool[] = [
  {
    slug: "gemini-image-watermark-remover",
    ai: "Gemini",
    brand: "Google Gemini",
    watermarkType: "SynthID + IPTC/EXIF metadata",
    description:
      "Google Gemini images carry SynthID (an invisible pixel-level signal) plus IPTC and EXIF metadata tags identifying the model. Our tool removes metadata-level signals. SynthID itself is steganographic and survives most edits.",
    longDescription:
      "Gemini images use a layered provenance system. The headline marker is metadata — IPTC tags (`Source: Google`, `Credit: Made with Google AI`) and EXIF fields that any forensic scanner instantly picks up. We strip those by canvas re-encoding. Note: SynthID, Google's perceptual watermark, is embedded in pixels and is designed to survive cropping, resizing and common edits — there is no client-side tool that defeats it.",
    hasC2PA: false,
  },
  {
    slug: "dalle-image-watermark-remover",
    ai: "DALL-E",
    brand: "OpenAI DALL-E",
    watermarkType: "C2PA metadata (same as ChatGPT)",
    description:
      "DALL-E 3 images delivered through ChatGPT or the OpenAI API include the same C2PA / JUMBF metadata as ChatGPT images. Our tool removes it identically.",
    longDescription:
      "DALL-E 3 outputs include a JUMBF box embedding C2PA Content Credentials — the cryptographic chain that says 'this image was generated by OpenAI'. Because ChatGPT now uses DALL-E (and gpt-image-1) as its image backend, the byte-level signature is identical. Drop a DALL-E image into our tool and it is detected and stripped the same way.",
    hasC2PA: true,
  },
  {
    slug: "sora-image-watermark-remover",
    ai: "Sora",
    brand: "OpenAI Sora",
    watermarkType: "C2PA metadata + visible Sora corner mark",
    description:
      "OpenAI Sora outputs include C2PA metadata identical to ChatGPT. The visible corner mark on Sora videos is pixel-level and cannot be removed with metadata stripping.",
    longDescription:
      "Sora is OpenAI's video and image generator. Sora frames and exported stills carry C2PA Content Credentials in the same JUMBF format as ChatGPT — we remove these completely. The animated Sora logo that appears in the corner of generated videos is rendered into pixels at export time and would require video editing software to remove visually.",
    hasC2PA: true,
  },
  {
    slug: "midjourney-watermark-remover",
    ai: "Midjourney",
    brand: "Midjourney",
    watermarkType: "Discord-side metadata, no C2PA",
    description:
      "Midjourney does not embed C2PA metadata. Their outputs carry minimal EXIF and Discord-attachment headers, plus the public gallery filename. Use a generic EXIF stripper.",
    longDescription:
      "Midjourney's primary 'watermark' is social: the prompt and creator are public on midjourney.com unless you have a Pro plan with Stealth Mode. The actual files carry sparse EXIF data and a Discord CDN URL in the filename. There is no JUMBF box and no C2PA signature to detect. If you want clean files, our tool will still re-encode the image and strip EXIF — but Midjourney is not the primary use case.",
    hasC2PA: false,
  },
  {
    slug: "grok-image-watermark-remover",
    ai: "Grok",
    brand: "xAI Grok",
    watermarkType: "Visible 'Grok' corner mark, sparse metadata",
    description:
      "xAI Grok adds a visible 'Grok' label in the corner of generated images and minimal metadata. Removing the visible label requires image editing software.",
    longDescription:
      "Grok (xAI) takes a different approach: instead of invisible C2PA metadata, it brands images with a small visible 'Grok' wordmark in one corner. Metadata is sparse — there is no JUMBF box. Our tool will re-encode the file and strip metadata, but the visible corner mark requires Photoshop, GIMP, or an AI inpainting tool to remove from pixels.",
    hasC2PA: false,
  },
  {
    slug: "stable-diffusion-watermark-remover",
    ai: "Stable Diffusion",
    brand: "Stable Diffusion / Stability AI",
    watermarkType: "Optional invisible-watermark library + PNG metadata",
    description:
      "Stable Diffusion (depending on the UI) writes prompt, model and seed into PNG text chunks and may apply Stability's invisible-watermark library. We strip the PNG metadata.",
    longDescription:
      "Stable Diffusion outputs through Automatic1111, ComfyUI and similar UIs embed your prompt, negative prompt, seed, sampler and model hash as PNG tEXt chunks — anyone with a metadata viewer can read your entire workflow. The official Stability release also applies their invisible-watermark library by default. Our canvas re-encoder removes all PNG text metadata. The invisible-watermark layer is pixel-level and partially survives re-encoding.",
    hasC2PA: false,
  },
];
