/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhatIsC2paMetadataIndexRouteImport } from './routes/what-is-c2pa-metadata/index'
import { Route as VerifyIndexRouteImport } from './routes/verify/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as HowToRemoveChatgptImageWatermarkIndexRouteImport } from './routes/how-to-remove-chatgpt-image-watermark/index'
import { Route as FaqIndexRouteImport } from './routes/faq/index'
import { Route as DetectIndexRouteImport } from './routes/detect/index'
import { Route as CookiePolicyIndexRouteImport } from './routes/cookie-policy/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as ChatgptWatermarkRemoverVsSlugIndexRouteImport } from './routes/chatgpt-watermark-remover-vs-$slug/index'
import { Route as ChatgptTextWatermarkRemoverIndexRouteImport } from './routes/chatgpt-text-watermark-remover/index'
import { Route as ChatgptImageWatermarkExplainedIndexRouteImport } from './routes/chatgpt-image-watermark-explained/index'
import { Route as C2paVsVisibleWatermarkIndexRouteImport } from './routes/c2pa-vs-visible-watermark/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BestChatgptImageWatermarkRemoversIndexRouteImport } from './routes/best-chatgpt-image-watermark-removers/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as RelatedToolIndexRouteImport } from './routes/$relatedTool/index'
import { Route as BlogSlugIndexRouteImport } from './routes/blog/$slug/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIsC2paMetadataIndexRoute = WhatIsC2paMetadataIndexRouteImport.update({
  id: '/what-is-c2pa-metadata/',
  path: '/what-is-c2pa-metadata/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToRemoveChatgptImageWatermarkIndexRoute =
  HowToRemoveChatgptImageWatermarkIndexRouteImport.update({
    id: '/how-to-remove-chatgpt-image-watermark/',
    path: '/how-to-remove-chatgpt-image-watermark/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FaqIndexRoute = FaqIndexRouteImport.update({
  id: '/faq/',
  path: '/faq/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectIndexRoute = DetectIndexRouteImport.update({
  id: '/detect/',
  path: '/detect/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyIndexRoute = CookiePolicyIndexRouteImport.update({
  id: '/cookie-policy/',
  path: '/cookie-policy/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatgptWatermarkRemoverVsSlugIndexRoute =
  ChatgptWatermarkRemoverVsSlugIndexRouteImport.update({
    id: '/chatgpt-watermark-remover-vs-$slug/',
    path: '/chatgpt-watermark-remover-vs-$slug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChatgptTextWatermarkRemoverIndexRoute =
  ChatgptTextWatermarkRemoverIndexRouteImport.update({
    id: '/chatgpt-text-watermark-remover/',
    path: '/chatgpt-text-watermark-remover/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChatgptImageWatermarkExplainedIndexRoute =
  ChatgptImageWatermarkExplainedIndexRouteImport.update({
    id: '/chatgpt-image-watermark-explained/',
    path: '/chatgpt-image-watermark-explained/',
    getParentRoute: () => rootRouteImport,
  } as any)
const C2paVsVisibleWatermarkIndexRoute =
  C2paVsVisibleWatermarkIndexRouteImport.update({
    id: '/c2pa-vs-visible-watermark/',
    path: '/c2pa-vs-visible-watermark/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BestChatgptImageWatermarkRemoversIndexRoute =
  BestChatgptImageWatermarkRemoversIndexRouteImport.update({
    id: '/best-chatgpt-image-watermark-removers/',
    path: '/best-chatgpt-image-watermark-removers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatedToolIndexRoute = RelatedToolIndexRouteImport.update({
  id: '/$relatedTool/',
  path: '/$relatedTool/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugIndexRoute = BlogSlugIndexRouteImport.update({
  id: '/blog/$slug/',
  path: '/blog/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$relatedTool/': typeof RelatedToolIndexRoute
  '/about/': typeof AboutIndexRoute
  '/best-chatgpt-image-watermark-removers/': typeof BestChatgptImageWatermarkRemoversIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/c2pa-vs-visible-watermark/': typeof C2paVsVisibleWatermarkIndexRoute
  '/chatgpt-image-watermark-explained/': typeof ChatgptImageWatermarkExplainedIndexRoute
  '/chatgpt-text-watermark-remover/': typeof ChatgptTextWatermarkRemoverIndexRoute
  '/chatgpt-watermark-remover-vs-$slug/': typeof ChatgptWatermarkRemoverVsSlugIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/cookie-policy/': typeof CookiePolicyIndexRoute
  '/detect/': typeof DetectIndexRoute
  '/faq/': typeof FaqIndexRoute
  '/how-to-remove-chatgpt-image-watermark/': typeof HowToRemoveChatgptImageWatermarkIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/what-is-c2pa-metadata/': typeof WhatIsC2paMetadataIndexRoute
  '/blog/$slug/': typeof BlogSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$relatedTool': typeof RelatedToolIndexRoute
  '/about': typeof AboutIndexRoute
  '/best-chatgpt-image-watermark-removers': typeof BestChatgptImageWatermarkRemoversIndexRoute
  '/blog': typeof BlogIndexRoute
  '/c2pa-vs-visible-watermark': typeof C2paVsVisibleWatermarkIndexRoute
  '/chatgpt-image-watermark-explained': typeof ChatgptImageWatermarkExplainedIndexRoute
  '/chatgpt-text-watermark-remover': typeof ChatgptTextWatermarkRemoverIndexRoute
  '/chatgpt-watermark-remover-vs-$slug': typeof ChatgptWatermarkRemoverVsSlugIndexRoute
  '/contact': typeof ContactIndexRoute
  '/cookie-policy': typeof CookiePolicyIndexRoute
  '/detect': typeof DetectIndexRoute
  '/faq': typeof FaqIndexRoute
  '/how-to-remove-chatgpt-image-watermark': typeof HowToRemoveChatgptImageWatermarkIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/terms': typeof TermsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/verify': typeof VerifyIndexRoute
  '/what-is-c2pa-metadata': typeof WhatIsC2paMetadataIndexRoute
  '/blog/$slug': typeof BlogSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$relatedTool/': typeof RelatedToolIndexRoute
  '/about/': typeof AboutIndexRoute
  '/best-chatgpt-image-watermark-removers/': typeof BestChatgptImageWatermarkRemoversIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/c2pa-vs-visible-watermark/': typeof C2paVsVisibleWatermarkIndexRoute
  '/chatgpt-image-watermark-explained/': typeof ChatgptImageWatermarkExplainedIndexRoute
  '/chatgpt-text-watermark-remover/': typeof ChatgptTextWatermarkRemoverIndexRoute
  '/chatgpt-watermark-remover-vs-$slug/': typeof ChatgptWatermarkRemoverVsSlugIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/cookie-policy/': typeof CookiePolicyIndexRoute
  '/detect/': typeof DetectIndexRoute
  '/faq/': typeof FaqIndexRoute
  '/how-to-remove-chatgpt-image-watermark/': typeof HowToRemoveChatgptImageWatermarkIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/what-is-c2pa-metadata/': typeof WhatIsC2paMetadataIndexRoute
  '/blog/$slug/': typeof BlogSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/$relatedTool/'
    | '/about/'
    | '/best-chatgpt-image-watermark-removers/'
    | '/blog/'
    | '/c2pa-vs-visible-watermark/'
    | '/chatgpt-image-watermark-explained/'
    | '/chatgpt-text-watermark-remover/'
    | '/chatgpt-watermark-remover-vs-$slug/'
    | '/contact/'
    | '/cookie-policy/'
    | '/detect/'
    | '/faq/'
    | '/how-to-remove-chatgpt-image-watermark/'
    | '/privacy/'
    | '/terms/'
    | '/tools/'
    | '/verify/'
    | '/what-is-c2pa-metadata/'
    | '/blog/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/$relatedTool'
    | '/about'
    | '/best-chatgpt-image-watermark-removers'
    | '/blog'
    | '/c2pa-vs-visible-watermark'
    | '/chatgpt-image-watermark-explained'
    | '/chatgpt-text-watermark-remover'
    | '/chatgpt-watermark-remover-vs-$slug'
    | '/contact'
    | '/cookie-policy'
    | '/detect'
    | '/faq'
    | '/how-to-remove-chatgpt-image-watermark'
    | '/privacy'
    | '/terms'
    | '/tools'
    | '/verify'
    | '/what-is-c2pa-metadata'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/$relatedTool/'
    | '/about/'
    | '/best-chatgpt-image-watermark-removers/'
    | '/blog/'
    | '/c2pa-vs-visible-watermark/'
    | '/chatgpt-image-watermark-explained/'
    | '/chatgpt-text-watermark-remover/'
    | '/chatgpt-watermark-remover-vs-$slug/'
    | '/contact/'
    | '/cookie-policy/'
    | '/detect/'
    | '/faq/'
    | '/how-to-remove-chatgpt-image-watermark/'
    | '/privacy/'
    | '/terms/'
    | '/tools/'
    | '/verify/'
    | '/what-is-c2pa-metadata/'
    | '/blog/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RelatedToolIndexRoute: typeof RelatedToolIndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  BestChatgptImageWatermarkRemoversIndexRoute: typeof BestChatgptImageWatermarkRemoversIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  C2paVsVisibleWatermarkIndexRoute: typeof C2paVsVisibleWatermarkIndexRoute
  ChatgptImageWatermarkExplainedIndexRoute: typeof ChatgptImageWatermarkExplainedIndexRoute
  ChatgptTextWatermarkRemoverIndexRoute: typeof ChatgptTextWatermarkRemoverIndexRoute
  ChatgptWatermarkRemoverVsSlugIndexRoute: typeof ChatgptWatermarkRemoverVsSlugIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  CookiePolicyIndexRoute: typeof CookiePolicyIndexRoute
  DetectIndexRoute: typeof DetectIndexRoute
  FaqIndexRoute: typeof FaqIndexRoute
  HowToRemoveChatgptImageWatermarkIndexRoute: typeof HowToRemoveChatgptImageWatermarkIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
  WhatIsC2paMetadataIndexRoute: typeof WhatIsC2paMetadataIndexRoute
  BlogSlugIndexRoute: typeof BlogSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-is-c2pa-metadata/': {
      id: '/what-is-c2pa-metadata/'
      path: '/what-is-c2pa-metadata'
      fullPath: '/what-is-c2pa-metadata/'
      preLoaderRoute: typeof WhatIsC2paMetadataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-remove-chatgpt-image-watermark/': {
      id: '/how-to-remove-chatgpt-image-watermark/'
      path: '/how-to-remove-chatgpt-image-watermark'
      fullPath: '/how-to-remove-chatgpt-image-watermark/'
      preLoaderRoute: typeof HowToRemoveChatgptImageWatermarkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/': {
      id: '/faq/'
      path: '/faq'
      fullPath: '/faq/'
      preLoaderRoute: typeof FaqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detect/': {
      id: '/detect/'
      path: '/detect'
      fullPath: '/detect/'
      preLoaderRoute: typeof DetectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy/': {
      id: '/cookie-policy/'
      path: '/cookie-policy'
      fullPath: '/cookie-policy/'
      preLoaderRoute: typeof CookiePolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatgpt-watermark-remover-vs-$slug/': {
      id: '/chatgpt-watermark-remover-vs-$slug/'
      path: '/chatgpt-watermark-remover-vs-$slug'
      fullPath: '/chatgpt-watermark-remover-vs-$slug/'
      preLoaderRoute: typeof ChatgptWatermarkRemoverVsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatgpt-text-watermark-remover/': {
      id: '/chatgpt-text-watermark-remover/'
      path: '/chatgpt-text-watermark-remover'
      fullPath: '/chatgpt-text-watermark-remover/'
      preLoaderRoute: typeof ChatgptTextWatermarkRemoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatgpt-image-watermark-explained/': {
      id: '/chatgpt-image-watermark-explained/'
      path: '/chatgpt-image-watermark-explained'
      fullPath: '/chatgpt-image-watermark-explained/'
      preLoaderRoute: typeof ChatgptImageWatermarkExplainedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c2pa-vs-visible-watermark/': {
      id: '/c2pa-vs-visible-watermark/'
      path: '/c2pa-vs-visible-watermark'
      fullPath: '/c2pa-vs-visible-watermark/'
      preLoaderRoute: typeof C2paVsVisibleWatermarkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-chatgpt-image-watermark-removers/': {
      id: '/best-chatgpt-image-watermark-removers/'
      path: '/best-chatgpt-image-watermark-removers'
      fullPath: '/best-chatgpt-image-watermark-removers/'
      preLoaderRoute: typeof BestChatgptImageWatermarkRemoversIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$relatedTool/': {
      id: '/$relatedTool/'
      path: '/$relatedTool'
      fullPath: '/$relatedTool/'
      preLoaderRoute: typeof RelatedToolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug/': {
      id: '/blog/$slug/'
      path: '/blog/$slug'
      fullPath: '/blog/$slug/'
      preLoaderRoute: typeof BlogSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RelatedToolIndexRoute: RelatedToolIndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  BestChatgptImageWatermarkRemoversIndexRoute:
    BestChatgptImageWatermarkRemoversIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  C2paVsVisibleWatermarkIndexRoute: C2paVsVisibleWatermarkIndexRoute,
  ChatgptImageWatermarkExplainedIndexRoute:
    ChatgptImageWatermarkExplainedIndexRoute,
  ChatgptTextWatermarkRemoverIndexRoute: ChatgptTextWatermarkRemoverIndexRoute,
  ChatgptWatermarkRemoverVsSlugIndexRoute:
    ChatgptWatermarkRemoverVsSlugIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  CookiePolicyIndexRoute: CookiePolicyIndexRoute,
  DetectIndexRoute: DetectIndexRoute,
  FaqIndexRoute: FaqIndexRoute,
  HowToRemoveChatgptImageWatermarkIndexRoute:
    HowToRemoveChatgptImageWatermarkIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  VerifyIndexRoute: VerifyIndexRoute,
  WhatIsC2paMetadataIndexRoute: WhatIsC2paMetadataIndexRoute,
  BlogSlugIndexRoute: BlogSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
